#!/usr/bin/env python3
"""
Parse a SteamCMD app_info_print dump and extract the public branch build ID.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import vdf


def fail(message: str, *, raw_text: str | None = None, preview_lines: int = 30) -> "NoReturn":
    print(f"Error: {message}", file=sys.stderr)
    if raw_text is not None:
        preview = "\n".join(raw_text.splitlines()[:preview_lines]).strip()
        if preview:
            print("----- app_info preview -----", file=sys.stderr)
            print(preview, file=sys.stderr)
            print("----- end preview -----", file=sys.stderr)
    raise SystemExit(1)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Extract the Steam public branch build ID from a SteamCMD dump.",
    )
    parser.add_argument(
        "app_info_path",
        type=Path,
        help="Path to the app_info.txt file generated by steamcmd.",
    )
    parser.add_argument(
        "--app-id",
        required=True,
        help="Steam app ID to extract from the dump.",
    )
    parser.add_argument(
        "--branch",
        default="public",
        help="Branch name to inspect. Defaults to public.",
    )
    parser.add_argument(
        "--preview-lines",
        type=int,
        default=30,
        help="How many raw lines to print on failure.",
    )
    return parser.parse_args()


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        fail(f"Unable to read SteamCMD output file {path}: {exc}")


def extract_app_block(raw_text: str, app_id: str) -> str:
    marker = re.search(rf'(?m)^[ \t]*"{re.escape(app_id)}"[ \t]*$', raw_text)
    if marker is None:
        raise ValueError(f'Unable to find a VDF block for app "{app_id}"')

    brace_start = raw_text.find("{", marker.end())
    if brace_start == -1:
        raise ValueError(f'Unable to find the opening brace for app "{app_id}"')

    depth = 0
    in_string = False
    escaped = False
    for index in range(brace_start, len(raw_text)):
        char = raw_text[index]
        if in_string:
            if escaped:
                escaped = False
            elif char == "\\":
                escaped = True
            elif char == '"':
                in_string = False
            continue

        if char == '"':
            in_string = True
            continue
        if char == "{":
            depth += 1
            continue
        if char == "}":
            depth -= 1
            if depth == 0:
                return raw_text[marker.start() : index + 1]

    raise ValueError(f'Unable to find the closing brace for app "{app_id}"')


def parse_vdf(candidate_text: str) -> Mapping[str, Any]:
    parsed = vdf.loads(candidate_text)
    if not isinstance(parsed, Mapping):
        raise ValueError("Parsed VDF payload is not a mapping")
    return parsed


def find_branch_build_id(node: Any, branch_name: str) -> str | None:
    if isinstance(node, Mapping):
        branches = node.get("branches")
        if isinstance(branches, Mapping):
            branch = branches.get(branch_name)
            if isinstance(branch, Mapping):
                build_id = branch.get("buildid")
                if isinstance(build_id, str) and build_id.isdigit():
                    return build_id

        for value in node.values():
            found = find_branch_build_id(value, branch_name)
            if found is not None:
                return found

    return None


def extract_build_id(raw_text: str, app_id: str, branch_name: str) -> str:
    candidates: list[Mapping[str, Any]] = []

    app_block = extract_app_block(raw_text, app_id)
    candidates.append(parse_vdf(app_block))

    try:
        parsed_full = parse_vdf(raw_text)
    except Exception:
        parsed_full = None
    if parsed_full is not None:
        candidates.append(parsed_full)

    for candidate in candidates:
        app_node = candidate.get(app_id, candidate)
        build_id = find_branch_build_id(app_node, branch_name)
        if build_id is not None:
            return build_id

    raise ValueError(
        f'Unable to locate branches/{branch_name}/buildid under app "{app_id}"'
    )


def main() -> None:
    args = parse_args()
    raw_text = read_text(args.app_info_path)

    try:
        build_id = extract_build_id(raw_text, args.app_id, args.branch)
    except Exception as exc:
        fail(str(exc), raw_text=raw_text, preview_lines=args.preview_lines)

    print(build_id)


if __name__ == "__main__":
    main()
